# AI Factory Frontend Worker - Service Bindings Architecture
# @WORKER: FrontendWorker  
# 🧱 Type: ConfigurationFile
# 📍 Path: wrangler.toml
# 🎯 Role: Frontend worker with service bindings to backend workers
# 💾 Storage: { kv: "session_store" }

name = "ai-factory-frontend-worker"
main = "src/index.ts"
compatibility_date = "2025-01-20"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
minify = true

# KV Storage binding for session management
[[kv_namespaces]]
binding = "SESSION_STORE"
id = "01fece0971104270a976cd1c1507afab"  # Use your existing KV namespace

# 🔥 SERVICE BINDINGS TO BACKEND WORKERS
[[services]]
binding = "ORCHESTRATOR"
service = "bitware-orchestrator"

[[services]]
binding = "TOPIC_RESEARCHER"
service = "bitware-topic-researcher"

[[services]]
binding = "RSS_LIBRARIAN"
service = "bitware-rss-source-finder"

[[services]]
binding = "FEED_FETCHER"
service = "bitware-feed-fetcher"

[[services]]
binding = "CONTENT_CLASSIFIER"  
service = "bitware-content-classifier"

[[services]]
binding = "REPORT_BUILDER"
service = "bitware-report-builder"

# Environment variables
[vars]
FRONTEND_VERSION = "2.0.0"
SESSION_TIMEOUT_HOURS = 24
ENABLE_DEBUG_LOGGING = true
CACHE_STATIC_ASSETS = true
STATIC_CACHE_TTL_SECONDS = 3600

# Development environment
[env.dev]
ENABLE_DEBUG_LOGGING = true
SESSION_TIMEOUT_HOURS = 1
CACHE_STATIC_ASSETS = false

# Production environment  
[env.production]
ENABLE_DEBUG_LOGGING = false
SESSION_TIMEOUT_HOURS = 24
CACHE_STATIC_ASSETS = true