name = "bitware-content-granulator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production", VERSION = "1.0.0" }

[env.staging]
vars = { ENVIRONMENT = "staging", VERSION = "1.0.0" }

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "content-granulator-db"
database_id = "f8b4192a-0c00-4504-b758-feecd9f8015a"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "TEMPLATE_CACHE"
id = "f8033cde336b4762bc5970fc2f1307a7"

[[kv_namespaces]]
binding = "JOB_CACHE"
id = "a41c43448f7c4fc28bc7f5a91ca19e64"

# R2 Storage for large structures
[[r2_buckets]]
binding = "STRUCTURE_STORAGE"
bucket_name = "granulator-structures"

# Service bindings for worker communication
[[services]]
binding = "KEY_ACCOUNT_MANAGER"
service = "bitware-key-account-manager"

# AI bindings
[ai]
binding = "AI"

# Note: Content Granulator is called via service binding from KAM
# KAM handles the queue consumption and calls this worker directly

# Secrets (add via wrangler secret put)
# OPENAI_API_KEY - OpenAI API key for AI operations
# CLAUDE_API_KEY - Claude (Anthropic) API key for AI operations
# SHARED_SECRET - Shared secret for worker authentication