name = "bitware-content-granulator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production", VERSION = "1.0.0" }

[env.staging]
vars = { ENVIRONMENT = "staging", VERSION = "1.0.0" }

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "content-granulator-db"
database_id = "YOUR_DATABASE_ID_HERE"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "TEMPLATE_CACHE"
id = "YOUR_TEMPLATE_CACHE_ID"

[[kv_namespaces]]
binding = "JOB_CACHE"
id = "YOUR_JOB_CACHE_ID"

# R2 Storage for large structures
[[r2_buckets]]
binding = "STRUCTURE_STORAGE"
bucket_name = "granulator-structures"

# Service bindings for worker communication
[[services]]
binding = "KEY_ACCOUNT_MANAGER"
service = "bitware-key-account-manager"

[[services]]
binding = "ORCHESTRATOR"
service = "bitware-orchestrator-v2"

# Secrets (add via wrangler secret put)
# OPENAI_API_KEY - OpenAI API key for AI operations
# SHARED_SECRET - Shared secret for worker authentication