name = "ai-factory-frontend"
compatibility_date = "2025-01-20"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "BITWARE_SESSION_STORE"
id = "4581e54c54184e3686b3e70f2f61936b"

[[services]]
binding = "KEY_ACCOUNT_MANAGER"
service = "bitware-key-account-manager"

[[services]]
binding = "CONTENT_GRANULATOR"
service = "bitware-content-granulator"

[vars]
KEY_ACCOUNT_MANAGER_URL = "https://bitware-key-account-manager.jhaladik.workers.dev"
GRANULATOR_URL = "https://bitware-content-granulator.jhaladik.workers.dev"
WORKER_SECRET = "internal-worker-auth-token-2024"