name = "ai-factory-frontend"
compatibility_date = "2025-01-20"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "BITWARE_SESSION_STORE"
id = "4581e54c54184e3686b3e70f2f61936b"

[[services]]
binding = "ORCHESTRATOR"
service = "bitware-orchestrator"

[vars]
ORCHESTRATOR_URL = "https://bitware-orchestrator.jhaladik.workers.dev"
TOPIC_RESEARCHER_URL = "https://bitware-topic-researcher.jhaladik.workers.dev"
RSS_LIBRARIAN_URL = "https://bitware-rss-source-finder.jhaladik.workers.dev"
FEED_FETCHER_URL = "https://bitware-feed-fetcher.jhaladik.workers.dev"
CONTENT_CLASSIFIER_URL = "https://bitware-content-classifier.jhaladik.workers.dev"
REPORT_BUILDER_URL = "https://bitware-report-builder.jhaladik.workers.dev"