name = "bitware-content-generator"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
VERSION = "1.0.0"
MAX_CONCURRENT_GENERATIONS = "5"
DEFAULT_MODEL = "gpt-4o-mini"
QUALITY_THRESHOLD = "75"
MAX_TOKENS_PER_REQUEST = "4000"
DEFAULT_TEMPERATURE = "0.7"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "content-generator-db"
database_id = "10c0739d-64f2-4560-ab37-13df86542feb"

# KV Namespaces
[[kv_namespaces]]
binding = "CONTENT_CACHE"
id = "59a446fdcfa6432eb728fdce43a33674"

[[kv_namespaces]]
binding = "JOB_STATUS"
id = "cda5dfae203646d5b34ce54f8736547c"

[[kv_namespaces]]
binding = "PROMPT_CACHE"
id = "e27860ba2a4948f0bb6ff458761ec63e"

# R2 Bucket
[[r2_buckets]]
binding = "CONTENT_STORAGE"
bucket_name = "content-generator-storage"

# Service Bindings
[[services]]
binding = "KEY_ACCOUNT_MANAGER"
service = "bitware-key-account-manager"

[[services]]
binding = "CONTENT_GRANULATOR"
service = "bitware-content-granulator"

# AI Binding for Cloudflare AI
[ai]
binding = "AI"

# Staging Environment
[env.staging]
name = "bitware-content-generator-staging"
vars = { ENVIRONMENT = "staging", VERSION = "1.0.0-staging" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "content-generator-db-staging"
database_id = "content-generator-db-staging-id"

[[env.staging.kv_namespaces]]
binding = "CONTENT_CACHE"
id = "content-cache-staging-id"

[[env.staging.kv_namespaces]]
binding = "JOB_STATUS"
id = "job-status-staging-id"

[[env.staging.kv_namespaces]]
binding = "PROMPT_CACHE"
id = "prompt-cache-staging-id"

[[env.staging.r2_buckets]]
binding = "CONTENT_STORAGE"
bucket_name = "content-generator-storage-staging"