# ===========================================
# Universal Researcher 2.0 - Wrangler Configuration
# ===========================================

name = "bitware-universal-researcher"
main = "index.ts"
compatibility_date = "2025-01-20"

# ===========================================
# D1 Database Configuration
# ===========================================

[[d1_databases]]
binding = "UNIVERSAL_DISCOVERY_DB"
database_name = "universal-discovery-db"
database_id = "691ef834-9e9e-4d5a-b278-2c8ef0f9ed66"

# ===========================================
# KV Storage Configuration  
# ===========================================

[[kv_namespaces]]
binding = "DISCOVERY_CACHE"
id = "598b271f9b5147e9a72f3a72498fdb45"

# ===========================================
# Environment Variables
# ===========================================

[vars]
MAX_SOURCES_PER_PLATFORM = "20"
QUALITY_THRESHOLD = "0.7"
CACHE_TTL_SECONDS = "3600"
AI_MODEL = "gpt-4o-mini"

# ===========================================
# Production Environment
# ===========================================

[env.production]
name = "bitware-universal-researcher"

[env.production.vars]
MAX_SOURCES_PER_PLATFORM = "50"
QUALITY_THRESHOLD = "0.8"
CACHE_TTL_SECONDS = "7200"

# ===========================================
# Development Environment
# ===========================================

[env.development]
name = "bitware-universal-researcher-dev"

[env.development.vars]
MAX_SOURCES_PER_PLATFORM = "10"
QUALITY_THRESHOLD = "0.6"
CACHE_TTL_SECONDS = "300"

# ===========================================
# Required Secrets (Set via wrangler secret put)
# ===========================================

# wrangler secret put CLIENT_API_KEY
# wrangler secret put WORKER_SHARED_SECRET
# wrangler secret put OPENAI_API_KEY
# wrangler secret put YOUTUBE_API_KEY (optional)
# wrangler secret put GOOGLE_SEARCH_API_KEY (optional)
# wrangler secret put GOOGLE_SEARCH_ENGINE_ID (optional)